name: CI

on: push

jobs:
  build:
    name: PharBuilder
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download pharbuilder
        uses: dsaltares/fetch-gh-release-asset@0.06
        with:
          file: "pharbuilder"
          repo: NetherGamesMC/pharbuilder-rs
          version: "tags/0.1.0"
          token: ${{ secrets.ng_token }}
      - name: Build
        run: |
          echo Building...
          chmod +x pharbuilder
          ./pharbuilder --input . --out InvMenu.phar
      - name: Upload
        uses: actions/upload-artifact@v2.2.4
        with:
          name: InvMenu
          path: InvMenu.phar
